version: "3.9"
services:
  auth:
    build: auth
    container_name: auth
    ports:
      - "5000:5000"
    volumes:
      - ./auth:/app
    links:
      - auth-cassandra

  profile:
    build: profile
    container_name: profile
    ports:
      - "5001:5001"
    volumes:
      - ./profile:/app
    links:
      - profile-cassandra

  product:
    build: product
    container_name: product
    ports:
      - "5003:5003"
    volumes:
      - ./product:/app
    links:
      - product-es

  auth-cassandra:
    image: cassandra:4.0
    container_name: auth-cassandra
    ports:
      - "9042:9042"
  profile-cassandra:
    image: cassandra:4.0
    container_name: profile-cassandra
    ports:
      - "9043:9042"

  product-es:
    container_name: product-es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
